name: Build and Deploy

on:
  push:
    branches:
    - main
  schedule:
  - cron: '0 */2 * * *'
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v5
      with:
        node-version: 22
    - run: npm ci
    - run: npm link
    - env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: betor-catalog -b ${{ vars.BETOR_API_URL }} -a ${{ secrets.BETOR_API_AUTHORIZATION }} build-items
    - run: betor-catalog build
    - run: cp src/_data/*.json src/static/data
    - run: npm install surge
    - run: npx surge dist ${{ vars.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
    - uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
